# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -DskipTests -Dgpg.skip deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
        
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v1
      with: # running setup-java again overwrites the settings.xml
        java-version: 1.8
        server-id: SERVER_ID # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: SERVER_USERNAME # env variable for username in deploy
        server-password: SERVER_PASSWORD # env variable for token in deploy

    - name: Publish to Apache Maven Central
      run: mvn -B -e -X deploy -DskipTests -Dgpg.skip -s $GITHUB_WORKSPACE/settings.xml 
      env:
        SERVER_ID: ${{ secrets.ServerId }}
        SERVER_USERNAME: ${{ secrets.ServerUser }}
        SERVER_PASSWORD: ${{ secrets.ServerPassword }}
